### ISSUE TITLE
Consider Using Petals

### ISSUE THREAD

**Issue by derevirn** [eellak/glossAPI#5]
Petals is a distributed P2P network that lets you train and use Large Language Models, without relying on expensive cloud infrastructure. The philosophy is similar to BitTorrent, and each user contributes some computational resources, while being able to utilize the network for his own purposes. I think this architecture is optimal for this open source project, so I suggest checking it out here: [Petals](https://petals.dev/)

**Comment by ninagial** [comment]
Πράγματι μας ενδιαφέρει, θα το δούμε. Αυτή τη στιγμή προέχει η χαρτογράφηση των χρήσιμων κειμενικών δεδομένων.
