### ISSUE TITLE
Δημιουργία chatbot

### ISSUE THREAD

**Issue by GEORGE2110** [eellak/glossAPI#6]
Προσπαθώ να εφαρμόσω το tutorial του openai "How to build an AI that can answer questions about your website ;Αυτή τη στιγμή πειραματίζομαι με μία ενότητα του site του ΕΛΛΑΚ το “τί είναι το ΕΛΛΑΚ” αυτό που θέλω να πετύχω είναι να κάνω το ίδιο π.χ με τα ΦΕΚ δηλαδή ένα εκπαιδευμένο  chat bot το οποίο θα απαντά σε ερωτήσεις σχετικά με έναν ορισμένο νόμο χρησιμοποιώντας για παράδειγμα τα FAQS που υπάρχουν σε σελίδες υπουργείων και οργανισμών. Έχω δημιουργήσει ένα μικρό text για την ενότητα του ΕΛΛΑΚ αλλά έχω πρόβλημα με τον κώδικα διότι δεν τρέχει (αυτή τη στιγμή βρίσκομαι ακόμη στο στάδιο του API request έχοντας πρώτα δοκιμάσει και τα επόμενα βήματα δηλαδή τη μετατροπή του text σε csv)  Σημειώνω ότι έχω κάνει όλα τα προβλεπόμενα δηλαδή τις εγκαταστάσεις στον υπολογιστή μου χρησιμοποιώντας το pip install και επίσης έχω εκδώσει και API key.  Εάν βρίσκεται την ιδέα μου ενδιαφέρουσα προτείνω τη συγκρότηση ομάδας για τη δημιουργία project

**Comment by GEORGE2110** [comment]
Ευχαριστώ που απαντίσατε στο σχόλιο μου, εννοείτε να ανεβάσω κάποιο κώδικα?

**Comment by ninagial** [comment]
Κατ' αρχήν ρόλος αυτού του αποθετηρίου δεν μπορεί σε καμία περίπτωση να είναι να παρέχουμε καθοδήγηση σε ανώνυμα αιτήματα για τεχνική υποστήριξη σε έργα τα οποία δεν είναι αναρτημένα, δεν διανέμονται με τις αρχές του ανοικτού λογισμικού, και δεν αποτελούν μέρος της συγκεκριμένης προσπάθειας. Υπάρχουν άλλα κανάλια για αυτό. Ως εκ τούτου δεν έχει διαφορά είτε ανεβάσετε κώδικα είτε όχι, εκτός αν θέλετε να συνεισφέρετε με κάποιο τρόπο στο αποθετήριο μέσα από τις δομημένες διαδικασίες, και κατά προτίμηση επώνυμα. Ελπίζω αυτό να ξεκαθαρίζει το θέμα.
